### ISSUE TITLE
New Full stack test with a Jetpack multisite instance

### ISSUE THREAD

**Issue by maxme** [wordpress-mobile/WordPress-FluxC-Android#101]
We should add 3 new tests to `ReleaseStack_SiteTestWPCom`:
- A wpcom account with a single Jetpack site connected
- A wpcom account with multiple Jetpack sites connected
- A wpcom account with a Jetpack multisites connected

**Comment by aforcier** [comment]
We should add similar tests to `ReleaseStack_SiteTestXMLRPC` (pending https://github.com/wordpress-mobile/WordPress-FluxC-Android/issues/207):

* A self-hosted site without Jetpack (check `isJetpack` etc statuses)
* A self-hosted site with Jetpack installed but not connected
* A self-hosted site with Jetpack installed and connected
 * Connected account is the one currently logged into
 * Connected account is not the one currently logged into

**Comment by aforcier** [comment]
Added in #292.
