### ISSUE TITLE
[Site Creation] Business Verticals - endpoint modification

### ISSUE THREAD

**Issue by malinajirka** [wordpress-mobile/WordPress-FluxC-Android#1011]
- Add a new attribute `is_new_user_vertical` to each vertical
- Add `limit` query parameter and set it to 5 for now

Example:
`GET /verticals?search=restaurant&locale=en&limit=5`

```
{
      "vertical_name": "Landscaping",
      "vertical_id": "a8c.0.1"
      "is_new_user_vertical": "false"
    }
```

**Comment by oguzkocer** [comment]
Fixed in #1049.
