### ISSUE TITLE
Fetch list items in batches

### ISSUE THREAD

**Issue by oguzkocer** [wordpress-mobile/WordPress-FluxC-Android#1126]
We currently only support fetching items from `ListStore` individually. Since `PostStore` is the only one that currently utilizes the `ListStore` and since we can't fetch posts in batches, this didn't matter. However, we should improve on this before we start implementing `ListStore` for other components.

We should also consider improving the way we fetch items. I don't know what's the best way to go about that, that's why I am not opening an issue for it right now, but since it's related to this issue, it's a good time to think about that as well.

My initial idea for how to handle this issue is to change `ListDataStoreInterface.fetchItem` to `ListDataStoreInterface.fetchItems` that accepts multiple ids and to call that from `PagedListPositionalDataSource.loadRangeInternal` as we currently do. Having said that, I'll think about if there is a better way to do this. I am also open to suggestions for it.

Note that we also have a backend request for fetching multiple posts at once and might be able to get that implemented which will increase the value of this issue.

cc @malinajirka for ideas ❤️

**Comment by malinajirka** [comment]
Thanks for creating the issue Oguz:). I don't have any better idea than what you proposed at the moment. However, I'll think about it and share my thoughts if I come up with something.

**Comment by oguzkocer** [comment]
With the changes in #1193 this is now easy to implement per feature.
