### ISSUE TITLE
Add support for filtering post lists by author

### ISSUE THREAD

**Issue by oguzkocer** [wordpress-mobile/WordPress-FluxC-Android#1161]
In order to implement https://github.com/wordpress-mobile/WordPress-Android/issues/5884, we need to add support for it in FluxC. Assuming I am not missing anything, this should be a fairly straightforward task and the following outline should work:

1. Add author filter to [PostListDescriptor](https://github.com/wordpress-mobile/WordPress-FluxC-Android/blob/develop/fluxc/src/main/java/org/wordpress/android/fluxc/model/list/PostListDescriptor.kt)
2. Handle the author filter in the post network clients
3. Add connected tests for both REST (WordPress.com/Jetpack) and XML-RPC sites [#](https://github.com/wordpress-mobile/WordPress-FluxC-Android/blob/develop/example/src/androidTest/java/org/wordpress/android/fluxc/release/ReleaseStack_PostListTestWpCom.kt), [#](https://github.com/wordpress-mobile/WordPress-FluxC-Android/blob/develop/example/src/androidTest/java/org/wordpress/android/fluxc/release/ReleaseStack_PostListTestXMLRPC.kt)

Note that `ListStore` uses `PostAction.FETCH_POST_LIST` to fetch the lists.

**Comment by drspaceboo** [comment]
It looks like XMLRPC doesn't support filtering based on the author. https://codex.wordpress.org/XML-RPC_WordPress_API/Posts#wp.getPost

Not sure what the next step is to resolve that issue.

**Comment by oguzkocer** [comment]
@drspaceboo That's a shame. Let's not have the author filter for XML-RPC sites. Let me know when you update your PR to reflect this change.

**Comment by oguzkocer** [comment]
Fixed in #1175.
