### ISSUE TITLE
XMLRPC not generated after cleaning project

### ISSUE THREAD

**Issue by drspaceboo** [wordpress-mobile/WordPress-FluxC-Android#1172]
I was setting up today to start contributing to this project however I ran into an issue where I couldn't just load the project up in Android Studio and build the example application.

It looks like some recent changes with Gradle has caused the `XMLRPC` class to not be generated by the annotation processors. The two changes that are causing the issue seem to be:

1. [Gradle is starting to ignore annotation processors that are on the `compile` path instead of on annotation processor path](https://discuss.gradle.org/t/regarding-the-annotation-processors-on-compile-classpath-warning-in-gradle-4-6/26144)
1. [Gradle now collapses multiple warnings that are generated when compiling trying to only show the most important ones.](https://docs.gradle.org/4.10.3/userguide/command_line_interface.html#sec:command_line_warnings)

The second was hiding the first issue, and when I ran `./gradlew example:assembleDebug --warning-mode all` to get all the warnings it ran the annotation processor correctly. After running that command the missing `XMLRPC` class now exists and can be found by Android Studio.

Currently the default build and run in Android Studio doesn't work for me as it deletes those generated files each time.

**Comment by aforcier** [comment]
@drspaceboo Thanks for digging into the issue! I'm not sure what the ultimate cause of it is, but we've been running into it on occasion for a while - it predates our using Gradle `4.6`, for example.

The best guess so far has been that it's an issue with `kapt` + Android Studio as it started happening sometime after we starting using `kapt` and it doesn't seem to happen when initiating clean builds from the commandline.

Usually running `./gradlew --stop` and then a `./gradlew build` from the commandline sorts things out.

Regardless though it would definitely be worth addressing that warning you mentioned - it's possible it's even related somehow even if it's been happening since before Gradle `4.6`.

I'm not sure I follow your steps for fixing it on your end though - did you do something to address the warning? Otherwise I'm not sure I follow why showing the warnings would have been enough to resolve the issue.

**Comment by aforcier** [comment]
After running `./gradlew example:assembleDebug --warning-mode all` I'm seeing a warning for `AutoServiceProcessor`. It looks like they recently released a new version which splits out the annotation artifact from the processor. I'm not sure doing that will solve the issue, but it might play better with `kapt`, and certainly it's worth addressing the warning regardless.

I'll look into this and open a PR you could maybe try @drspaceboo and see if that fixes your build from Android Studio - it happens to me pretty rarely so I don't expect I'll be able to confirm if this fixes it or not.

**Comment by drspaceboo** [comment]
Regarding other steps for fixing it on my end I ran into the issue building the example app and jumped into terminal to see if building from there would help. Running `./gradlew example:assembleDebug` I still got the issue, so I ran it will `--warning-mode all` set and it built correctly. I totally agree that it makes no sense why that would have helped, and at the time it consistently exhibited this behaviour. Going back to Android Studio to build would remove those files but running the command with the warnings showing would bring them back.

Today I tried you suggested commands `./gradlew --stop` and then `/gradlew build` and now I cannot replicated my original issue at all.

I tried a fresh clone of the repo and building but the issue did not crop up again. I think we can safely say that it was some sort of local state related to Gradle causing the issue and not the repository.

**Comment by aforcier** [comment]
Closing this as the AutoService annotation processor warnings since Gradle `4.6` have been addressed in #1173.

Hopefully the original issue of the occasionally ungenerated `XMLRPC.java` was also resolved by that PR, but time will tell. If it springs up again we'll open a new issue to track it.

**Comment by drspaceboo** [comment]
Hit the issue with XMLRPC not being generated with the change you made in the code.

Running the commands `./gradlew --stop` and then `/gradlew build` resolved the issue again. However there still seems to be something underlying causing this, either in Gradle or our own code.

**Comment by aforcier** [comment]
Well that was short lived 😞 Thanks for the report @drspaceboo - I opened https://github.com/wordpress-mobile/WordPress-FluxC-Android/issues/1179 to track the issue with the fix and what we know so far so it's easier to look up the problem in the future.
