### ISSUE TITLE
Trashing/Restoring post removes local changes

### ISSUE THREAD

**Issue by oguzkocer** [wordpress-mobile/WordPress-FluxC-Android#1207]
Since we save the remote version of the post when a post is deleted or restored we lose the local changes on it. Since we don't know what the local changes are, we probably want to change the status of the post to what we get from the remote.

**Comment by malinajirka** [comment]
Losing local changes can be quite inconvenient and I feel like we should do all we can to prevent it
- Easy win (probably easy:P)- replace "trash" action with "discard local changes" action (seems like an easy win with pretty good UX)
- Ideal plan - keep the changes through trash/restore 
- Fallback plan - show a warning dialog when you try to trash a post with local changes 

Wdyt @oguzkocer ?


cc @SylvesterWilmott

**Comment by oguzkocer** [comment]
I think we can start with trying to keep changes through trash/restore by changing their status in the DB with the local changes and if we find that doesn't behave as we expect it to, then start considering different actions. I think that'll make it easier to find those different actions because we'll have more info about when it does not work as expected.

Fwiw, I like the `Discard local changes` button over trash as we really shouldn't let users to trash a post with a local change. That may end up users complaining about not being able to trash the post because the trash button won't be visible before the local changes are trashed, so I am not sure.

**Comment by oguzkocer** [comment]
I fixed the issue for trashing posts in `issue/dont-remove-local-changes-on-trash-and-restore-post` branch, but haven't had a chance to do it for restore. I think a similar approach to this should work.

The restore action is no longer used except for undoing a trash action, so it's not as big of a problem right now, but still good to address before we merge things to `develop`.

**Comment by malinajirka** [comment]
I have pushed a similar approach for the restore action. However, unless I'm missing something I believe this approach has one issue. If we don't store the post from the remote into our local database and we just update its status, another fetch from the remote will always result in potential conflict.

1. Both local and remote posts have modified date "123"
2. We make local changes to the post
3. We trash the post -> server updates modified date of the remote post to "999" -> when we receive the response from the server, we just update the status of the local post 
4. Whenever we fetch the post in the future, a potential conflict will be always detected as the post has local changes and the modified date of the local post is "123" and the modified date of the remote post is "999"

Options I can think of:
1) update both status and modified date -> I think we shouldn't even consider this option as we could theoretically override remote changes
2) discard the local changes when we trash the post

I'd personally vote for option 2 - we can simply show a warning dialog and inform the user that they'll lose the local changes. I think the UX will be good enough and not a lot of users will see it anyway as most changes are synced with remote automatically + we'll hopefully add auto-sync feature in the offline support project and the significance of this issue will be even lower. Tbh I also feel like the fix could bite us in the future as it's not fool-proof and adds side effects to simple actions.

Wdyt @oguzkocer ?

**Comment by oguzkocer** [comment]
> If we don't store the post from the remote into our local database and we just update its status, another fetch from the remote will always result in potential conflict.

Yes. If we want to keep the local changes during a trash action, we'll need to let the user deal with the conflict later on. Hopefully this is not very likely to happen with us already forcing the post conflict resolution.

> discard the local changes when we trash the post

I am totally OK with this as long as we make that clear to the user. It's probably the best course of action for us for now. If we get feedback, either from Sylvester or other devs/testers, that this doesn't feel good, let's re-open this issue or open a new one and document why we opted for this solution and what to watch out for in a proper solution. (basically this discussion)

**Comment by SylvesterWilmott** [comment]
>discard the local changes when we trash the post

Absolutely this. Showing a dialog will be enough.

Body: Trashing this post will discard local changes, are you sure you want to continue?
Buttons: Cancel OK

**Comment by malinajirka** [comment]
Thanks Sylvester! ;)

Closing this issue as the solution needs to be implemented in the client's code. (https://github.com/wordpress-mobile/WordPress-Android/pull/9641)
