### ISSUE TITLE
PagedListWrapper isListEmpty ignores local items

### ISSUE THREAD

**Issue by malinajirka** [wordpress-mobile/WordPress-FluxC-Android#1210]
[IsListEmpty lambda](https://github.com/wordpress-mobile/WordPress-FluxC-Android/blob/685212bb2266484e69384662f4bdfffbcb46a079/fluxc/src/main/java/org/wordpress/android/fluxc/store/ListStore.kt#L111) doesn't take into account that class implementing ListItemDataSourceInterface can add items into the list - eg. local drafts. The result of the implementation is that "isListEmpty" returns true when the list contains only such items.

Detailed description with steps how to reproduce the behavior in WPAndroid can be found [here](https://github.com/wordpress-mobile/WordPress-Android/issues/9595).

**Comment by malinajirka** [comment]
@oguzkocer I'd personally bind `isEmpty` directly to `data: LiveData<PagedList<T>>` in the PagedListWrapper so we are sure it's always up to date. However, I'll leave the decision up to you as I'm not 100% sure I fully understand why we check the size against db.

**Comment by oguzkocer** [comment]
Fixed in #1212.
