### ISSUE TITLE
Add support for post/page remote autosave

### ISSUE THREAD

**Issue by maxme** [wordpress-mobile/WordPress-FluxC-Android#1247]
Add support for post/page remote autosave. This is a wpcom feature only. 

Add new field `autosave` fields to the PostModel and support the option to corresponding GET calls in the `PostRestClient`:

- We must support pulling `meta.data.autosave` fields from the GET call: `GET /rest/v1.1/sites/SITE_ID/posts/POST_ID?meta=autosave`.

New post store action to autosave:

- We must support posting `autosave` fields to the POST call: `POST /rest/v1.1/sites/SITE_ID/posts/POST_ID/autosave`.

**Comment by maxme** [comment]
Note there is some documentation on the v1.2 [corresponding POST call](https://developer.wordpress.com/docs/api/1.2/post/sites/%24site/posts/%24post_ID/): `POST /rest/v1.2/sites/$site/posts/$post_ID?autosave=true`

**Comment by yaelirub** [comment]
@malinajirka , can this ticket be closed?

**Comment by malinajirka** [comment]
Fixed in https://github.com/wordpress-mobile/WordPress-FluxC-Android/pull/1255
