### ISSUE TITLE
Move field comments to getters so they are shown in AS autocompletion

### ISSUE THREAD

**Issue by malinajirka** [wordpress-mobile/WordPress-FluxC-Android#1258]
Move field comments in PostModel to corresponding getters as suggested [here](https://github.com/wordpress-mobile/WordPress-FluxC-Android/pull/1255#discussion_r284794601)

**Comment by malinajirka** [comment]
@shiki I started moving the comments to the corresponding getters/setters, but tbh I'm not sure it's an improvement. I feel like the comments are mostly useful for developers who are editing these files. https://github.com/wordpress-mobile/WordPress-FluxC-Android/compare/issue/1247-remote-auto-save...auto-save-minor-refactoring?expand=1

I wish we could do something like this
```
/**
* My comment
*/
private boolean test;
```
and it'd automatically show the comment in autocompletion when no other javadoc comment is present on the corresponding getter/setter. 😞 

Wdyt?

**Comment by shiki** [comment]
You're right. It can be a lot of work. I guess the comments for private fields are fine for now. The ultimate fix is converting this to Kotlin. 😁 

With all that said, I don't think this is worth it to be in a PR. We can incrementally improve it in the future as we change things in `PostModel`. I'm sorry for leading you on this path. 

We can close this if you agree. 🙂

**Comment by malinajirka** [comment]
>The ultimate fix is converting this to Kotlin. 😁

💯 

>It can be a lot of work. 

It wasn't about the amount of work but more about whether it's actually an improvement. But I agree we should rather convert the file into kotlin as it'd solve all our issues.
