### ISSUE TITLE
Change compileSdkVersion to 28

### ISSUE THREAD

**Issue by nbradbury** [wordpress-mobile/WordPress-FluxC-Android#1264]
In order to migrate to AndroidX, the `compileSdkVersion` needs to be updated to 28. No change needs to be made to `targetSdkVersion`.

**Comment by wzieba** [comment]
hi @nbradbury, is it okay to close this issue? I think `compileSdkVersion` on every module in `FluxC` is already `28` or more:

<img width="237" alt="image" src="https://user-images.githubusercontent.com/5845095/114834355-c3488400-9dd0-11eb-99df-5384931fba8a.png">

**Comment by nbradbury** [comment]
Thanks for the reminder! Yes, we can close this.
