### ISSUE TITLE
Fetch only autosave.modifiedDate object instead of the whole meta object

### ISSUE THREAD

**Issue by malinajirka** [wordpress-mobile/WordPress-FluxC-Android#1277]
The introduction of the List Management component changed the way we fetch posts from the server. We basically first fetch just list of ids, modifiedDates and statuses -> if the PostModel in our local database has the same status and modified date, we don't fetch its detailed data. This approach saves tons of data and is also more performant.

However, we've started fetching the whole "meta" object [here](https://github.com/wordpress-mobile/WordPress-FluxC-Android/blob/1ec4e335986162af07901b124a032833a176ed3e/fluxc/src/main/java/org/wordpress/android/fluxc/network/rest/wpcom/post/PostRestClient.java#L113) - this change was introduced in [this PR](https://github.com/wordpress-mobile/WordPress-FluxC-Android/pull/1255) as we didn't come up with a better solution.

Ideal fix for this issue is to add support for requesting specific nested fields to the API -> we'd request just "meta.data.autosave.modified" instead of the whole meta object.

cc @shiki @maxme

**Comment by shiki** [comment]
Sounds good to me. @malinajirka, have you measured how big the `meta` objects can be?

**Comment by malinajirka** [comment]
The difference is significant. This is just an example + if you take into account the `autosave.content`  can be huge, I believe this ticket should have at least a medium priority.
<img width="453" alt="Screenshot 2019-05-30 at 19 04 18" src="https://user-images.githubusercontent.com/2261188/58650008-eae1f080-830d-11e9-86d1-6a97a233679a.png">

vs
<img width="349" alt="Screenshot 2019-05-30 at 19 05 04" src="https://user-images.githubusercontent.com/2261188/58650010-ee757780-830d-11e9-9e2c-f8bc014cfa7c.png">

**Comment by shiki** [comment]
Thank you. I agree. That is significant.

**Comment by maxme** [comment]
Sounds good to me. I had a look at the [API doc](https://developer.wordpress.com/docs/api/1.2/get/sites/%24site/posts/) and I'm not sure how this is doable.

I tried `meta=data.autosave.modified` and `meta=autosave.modified` but it doesn't work.

**Comment by malinajirka** [comment]
Yes, sorry. I should have been more explicit. This is not supported on the API at the moment. I created this ticket so we don't forget about it and propose the change to the API team.

**Comment by malinajirka** [comment]
The api change request is being discussed here - p3hLNG-14E-p2.

**Comment by shiki** [comment]
Fixed in #1379
