### ISSUE TITLE
Handle XML-RPC media filesize limits

### ISSUE THREAD

**Issue by aforcier** [wordpress-mobile/WordPress-FluxC-Android#142]
Some XML-RPC sites can have a very low media upload size limit (`2MB`, hopefully no less than that...). This seems to be dependent on the setting of `upload_max_filesize` in `php.ini`, which can have different defaults depending on the host. We'll need to make sure we detect and report this error accurately, when a media upload fails because it's larger than the size limit.

Also, since the [SiteStore integration](https://github.com/wordpress-mobile/WordPress-Android/pull/4455) is dropping the 'maxImageWidth' setting from WPAndroid, we'll eventually need a different (better) way to set a file size limit, especially for these sites where the upload will fail otherwise.

A setting in a future upload manager would be good, though we'll probably need a simpler shorter-term solution in the meantime.

**Comment by oguzkocer** [comment]
I've tried this in both a local installation as well as a remote one. It turns out the `upload_max_filesize` does not affect the xml-rpc calls. However, we do get an error if the file is large enough. Here are the details of that error:

Response header:
```
Date: Mon, 13 Mar 2017 09:03:09 GMT
Server: Apache/2.2.15 (Win32) PHP/5.3.2
X-Powered-By: PHP/5.3.2
Connection: close
Content-Length: 403
Content-Type: text/xml; charset=UTF-8
```

Response xml:
```
