### ISSUE TITLE
Checking for v4 revenue stats availability should check for v0.23 of the WooCommerce Admin plugin

### ISSUE THREAD

**Issue by nbradbury** [wordpress-mobile/WordPress-FluxC-Android#1447]
In #1446 we implemented a hotfix to handle breaking changes in the v0.23 release of the WooCommerce Admin plugin, but I believe we're not taking the plugin version into account when we check if the v4 revenue stats are available.

Related to this, if the v4 stats aren't available we show a message stating, "We have reverted to the old stats. To use the beta stats, please activate the WooCommerce Admin plugin with version 0.22 or higher." We just change that to 0.23.

**Comment by anitaa1990** [comment]
Closing this issue since WC-Admin has been merged into Woo 4.0 and we no longer depend on the WooCommerce Admin version alone to verify if v4 stats is available.
