### ISSUE TITLE
Woo: Woo API tests sometimes fail with 404 errors

### ISSUE THREAD

**Issue by rachelmcr** [wordpress-mobile/WordPress-FluxC-Android#1597]
We've had a couple nightly test runs for the Woo API tests fail with flaky failures. The failures are caused by unexpected 404 responses, but when re-running the tests they pass.

A couple examples:
* [27 May 2020](https://app.circleci.com/pipelines/github/wordpress-mobile/WordPress-FluxC-Android/2123/workflows/78ff7ea0-9c8e-4e3a-bd22-7777ad3c0970/jobs/6281/steps)
* [29 May 2020](https://app.circleci.com/pipelines/github/wordpress-mobile/WordPress-FluxC-Android/2136/workflows/9b27073e-0fe1-410b-9008-c0f6f0977b78/jobs/6313/steps)

We should investigate those failures to see if we can avoid them altogether, and perhaps consider re-running failed tests automatically to avoid the job failing due to flakiness.

**Comment by rachelmcr** [comment]
@bsessions85 Did you see any flakiness like this while developing these tests? Or any thoughts for how to mitigate it?

**Comment by bsessions85** [comment]
@rachelmcr I didn't see any issues, but if I had to come up with a theory it would be that the step to update the plugin isn't giving it enough time to update. I'll play with it a little bit today and see what I can come up with.

**Comment by bsessions85** [comment]
@rachelmcr I added a cron job that will hit the test site every hour so that the jobs don't build up and make this one take longer than the 2 minutes already allocated.

**Comment by rachelmcr** [comment]
Thanks @bsessions85! I'll keep an eye on the nightly runs and close this issue if it seems to be resolved.

**Comment by rachelmcr** [comment]
Closing since we haven't seen any failures in the past week. 👍
