### ISSUE TITLE
WC: Update just a product's attributes

### ISSUE THREAD

**Issue by nbradbury** [wordpress-mobile/WordPress-FluxC-Android#1912]
For WCAndroid, we need a way to update only a product's attributes. This could use the same call we use to update the product, except passing only its attributes, eg:

```
product {
   attributes: [
       {
           id: 3,
           name: "Size"
           options: [
               "S",
               "M",
               "L"
           ]
       }
   ] 
}
```
Note we want to save **all** attribute & term changes - both local and global - in one call. This can be done by simply including only the `attributes` section when updating a product.

So we need a method to accept a site model, remoteProductId, and a list of attributes (local and/or global) with their terms.

**Comment by ThomazFB** [comment]
Closing this issue since the fix is already merged
