### ISSUE TITLE
Remove `buildscript { ... }` from sub-projects `build.gradle` and use `Plugin DSL`

### ISSUE THREAD

**Issue by wzieba** [wordpress-mobile/WordPress-FluxC-Android#1960]
### The problem

Currently, when building a project we can see a Gradle warning: 

> The Kotlin Gradle plugin was loaded multiple times in different subprojects, which is not supported and may break the build.
This might happen in subprojects that apply the Kotlin plugins with the Gradle 'plugins { ... }' DSL if they specify explicit versions, even if the versions are equal.
Please add the Kotlin plugin to the common parent project or the root project, then remove the versions in the subprojects.
If the parent project does not need the plugin, add 'apply false' to the plugin line.
See: https://docs.gradle.org/current/userguide/plugins.html#sec:subprojects_plugins_dsl
The Kotlin plugin was loaded in the following projects: ':example', ':fluxc'

This is because we add a Kotlin plugin in `buildscript { ... }` in many modules. `buildscript { ... }` method adds dependencies to the whole project's buildscript. [Citing from `Gradle` documentation](https://docs.gradle.org/current/userguide/tutorial_using_tasks.html#sec:build_script_external_dependencies)

> For multi-project builds, the dependencies declared with a project’s `buildscript()` method are available to the build scripts of all its sub-projects.

### The solution

We could move `buildscript { ... }` to project's `build.gradle` file and remove `buildscript { ... }` from subprojects but this is sub-optimal solution. Using `buildscript { ... }` and `apply plugin: (...)` is a legacy way. [Documentation](https://docs.gradle.org/current/userguide/plugins.html#sec:old_plugin_application) or [Gradle Portal (see `legacy plugin application`)](https://plugins.gradle.org/plugin/org.jetbrains.kotlin.jvm) stands so.

I think we should move [to the recommended Plugin DSL](https://docs.gradle.org/current/userguide/plugins.html#sec:plugins_block). To do this we should:
1. Define all plugins in `pluginManagement { ... }` in `settings.gradle`
2. Apply plugins in `plugins { ... }` block
3. Remove `buildscript { ... }` block from sub-projects

**Comment by wzieba** [comment]
@wordpress-mobile/platform-9 what do you think about this?

**Comment by oguzkocer** [comment]
@wzieba Thank you for putting this together. As far as I know your suggestion of using `pluginManagement` is the "right" way to do this and we have started utilizing it in other places. Please feel free to work on the issue or open a Platform 9 request if you'd prefer we handle it.

**Comment by wzieba** [comment]
Thanks for the feedback @oguzkocer. I'll willingly handle it.

**Comment by mokagio** [comment]
Thank you @wzieba!
