### ISSUE TITLE
Allow for selecting WooCommerce site on sample FluxC app

### ISSUE THREAD

**Issue by wzieba** [wordpress-mobile/WordPress-FluxC-Android#2033]
If a user has more than 1 WooCommerce instances connected to the account, we should allow a user to select a site to which we'll send requests in the `Woo` section of the sample app.

**Comment by hafizrahman** [comment]
Some areas in the example app (like Woo -> Shipping Labels) do have the site selection option already, so it will be a matter of bringing that to other places too.
