### ISSUE TITLE
Jetpack handling over XML-RPC

### ISSUE THREAD

**Issue by aforcier** [wordpress-mobile/WordPress-FluxC-Android#207]
This issue includes Jetpack-related considerations we still need to address. This can probably be split off into sub-issues when we have our approach cleared up.
#### Self-hosted site Jetpack status

The main status a self-hosted site can have with respect to Jetpack and the current account are:
1. Jetpack is not installed
2. Jetpack installed, but not connected to any account
3. Jetpack installed, and connected, and the current WP.com account logged into has access
4. Jetpack installed, and connected, but the current WP.com account doesn’t have access
5. Edge cases like Jetpack is connected but we're unable to reach the site (Jetpack errors)

...
#### WPAndroid UI considerations

From a UI perspective, these four Jetpack cases should be handled WPAndroid-side as follows (when the user navigates to a REST-only part of the app, e.g. Stats):
1. Show a dialog: You must install Jetpack to see your stats in the apps (this site uses XMLRPC API)
2. Show a dialog: You must complete your Jetpack connection (this site uses XMLRPC API)
3. Here are your stats (this site uses REST API)
4. Show a dialog:  Sorry, we don't support multi WP.com connections (this site uses XMLRPC API) (if possible, tell them which WP.com account it is connected to)
#### SiteModel

We need to think about how much to represent in SiteModel, and how much to leave up to the host application.

There's currently an issue where self-hosted sites without Jetpack installed get [flagged](https://github.com/wordpress-mobile/WordPress-FluxC-Android/blob/5e52ac8cb074b1213e573ff46b2208154cb4f89f/fluxc/src/main/java/org/wordpress/android/fluxc/network/xmlrpc/site/SiteXMLRPCClient.java#L224) as `isJetpack = true`, and we're unable to distinguish the case of 'Jetpack not installed' from 'Jetpack installed but not connected'.

The `siteId` logic should probably be:

| Jetpack Status | `jetpack_client_id` value (`wp.getOptions`) | siteId should be | isJetpack |
| --- | --- | --- | --- |
| not installed | N/A (not returned) | -1 | false |
| installed, but not connected | 0 | 0 | ? |
| installed and connected | 123456 (the real .com site ID) | 123456 (the real .com site ID) | true? |
##### Questions
1. Do we set `SiteModel.isJetpack = true` if Jetpack is installed but not connected? Or should we add a new method `SiteModel.isJetpackConnected()`?
2. Is it meaningful for a self-hosted site to be flagged `isJetpack` if the current logged-in WP.com account can't access it?
3. Maybe we can dispel the confusion by renaming `isJetpack` to `isWPComAndJetpack`, and querying XML-RPC Jetpack status independently using `isJetpackInstalled()` and `isJetpackConnected()` (or just checking it manually through `getSiteId()`?
4. Additionally, should we can add a new `AccountStore` method like `AccountStore.userHasAccessToJetpackSite(SiteModel)`, so we can tell case 4 from case 3 without doing a lookup WPAndroid-side?

**Comment by aforcier** [comment]
We also have some conflict situations to resolve:

1. Log into WP.com account with Jetpack site, then add that Jetpack site as self-hosted --> crash (https://github.com/wordpress-mobile/WordPress-Android/pull/4455#issuecomment-242238265)
2. Log into Jetpack site as self-hosted, then log into WP.com account linked to it --> ?
3. Enable Jetpack on self-hosted site after it's been added to the app (https://github.com/wordpress-mobile/WordPress-FluxC-Android/issues/58)

**Comment by aforcier** [comment]
The three conflict situations are all resolved now - between #285 and #292 they've been fixed and we have tests for them.

Some of the original questions still need some work, however:

1. Should we distinguish non-Jetpack XML-RPC sites from sites with Jetpack active but not connected? (case 1 and 2 above, which we might want to provide different dialogs for inside the app eventually)
2. Should we still allow self-hosted sites to have `isJetpack() == true` when they are connected to a different WP.com account than the one the user is logged into? This might cause a few surprises down the road (see this note: https://github.com/wordpress-mobile/WordPress-FluxC-Android/pull/292#issuecomment-275165015)

**Comment by daniloercoli** [comment]
> Should we distinguish non-Jetpack XML-RPC sites from sites with Jetpack active but not connected? (case 1 and 2 above, which we might want to provide different dialogs for inside the app eventually)

Yes, Please :) 
There are cases where we need to point the user to the correct action/address/dialog. EX: if you tap Stats in the app. We should be aware if Jetpack is already installed on the site (but not connected to wpcom) or not installed.

**Comment by daniloercoli** [comment]
> Maybe we can dispel the confusion by renaming isJetpack to isWPComAndJetpack, and querying XML-RPC Jetpack status independently using isJetpackInstalled() and isJetpackConnected()

My 2 cents are on adding another method `isJetpackConnected()`. It seems self explanatory and easy to use for wp-android developers.

**Comment by daniloercoli** [comment]
Just an additional note on things I think we should fix in FluxC regarding Jetpack sites:
Each single module can be disabled on Jetpack sites. So, if we really want to provide a nice UX we need to synch that info as well (info are stored on wpcom). 
Real case usage: Stats and the REST API. They both could be disabled on the site, and to provide correct error messages we should be aware of that in wp-android. Ref: https://github.com/wordpress-mobile/WordPress-Android/pull/4929

**Comment by maxme** [comment]
Related comment on this issue: https://github.com/wordpress-mobile/WordPress-Android/pull/5044#issuecomment-276649866
