### ISSUE TITLE
MediaStore: error message from the APIs should be returned to OnMediaUploaded event

### ISSUE THREAD

**Issue by maxme** [wordpress-mobile/WordPress-FluxC-Android#209]
Example: try to upload an empty image the REST API replies with:

```
{
	"errors": [{
		"file": "",
		"error": "upload_error",
		"message": "File is empty. Please upload something more substantial."
	}]
}
```

results in an OnMediaUploaded.error as a GENERIC_ERROR with an empty message.

**Comment by aforcier** [comment]
Fixed in https://github.com/wordpress-mobile/WordPress-FluxC-Android/pull/325.
