### ISSUE TITLE
Push new media test

### ISSUE THREAD

**Issue by oguzkocer** [wordpress-mobile/WordPress-FluxC-Android#210]
It's unclear what `testPushNewMedia` in `ReleaseStack_MediaTestWPCom` is trying to achieve. If I remember correctly, we wrote that to test pushing a media that doesn't exist which would result in the media being uploaded. But it looks like it's changed in 110bc7455b756b515278677bd86bdea03460f4f7. It's now expecting a `PUSH_ERROR` which I don't understand why. We should either fix the test, explain what it's doing or remove it completely if it doesn't make sense anymore (maybe due to the pushing new media is not actually uploading).

What do you think @tonyr59h? /cc @maxme (since you reviewed the original PR)

**Comment by tonyr59h** [comment]
All fixed up via #233, friendly reminder for us to close it once it's been merged.

**Comment by oguzkocer** [comment]
@tonyr59h #233 is merged, but it doesn't seem to address the issue mentioned in the original description. Basically what the test does and it's naming doesn't match. I am happy to take this over, I just don't know what you originally was going for using a fail event for push media test.

**Comment by tonyr59h** [comment]
> I just don't know what you originally was going for using a fail event for push media test.

Originally the feature and test were written under the assumption that a `PUSH_MEDIA` action would automatically upload media if it didn't exist remotely. `testPushNewMedia` wasn't renamed and could definitely be more descriptive, but the test itself does verify that an error results from this scenario so I think it's still valid. Would renaming it to `testPushNonexistentMediaError` make sense?

**Comment by oguzkocer** [comment]
Yes, I think we should rename it, so we know we expect an error. If we do decide to upload the media if we get a `NOT_FOUND` error as you mentioned, we should build on this test and make sure we cover the upload part as well.

**Comment by oguzkocer** [comment]
This issue seems to have been resolved as we don't have a `testPushNewMedia` anymore. I think it's safe to close this one!
