### ISSUE TITLE
WCAndroidDatabase - Add Missing '7.json' Migration File to Database Schemas

### ISSUE THREAD

**Issue by ParaskP7** [wordpress-mobile/WordPress-FluxC-Android#2261]
As part of the [Issue/2252 wcordermodel taxlines #2253](https://github.com/wordpress-mobile/WordPress-FluxC-Android/pull/2253) PR, an upgrade to the `WCAndroidDatabase` occurred, from version `6` to `7` (see last [commit](https://github.com/wordpress-mobile/WordPress-FluxC-Android/pull/2253/commits/3cf2537c4f2d9496ad6a078ca420e18a9b29d4e1)).

When doing such an database upgrade, it is recommended to add an accompanying migration file to the database schema. For example, as part of a previous[ Fix precision of total refunds calculation #2240](https://github.com/wordpress-mobile/WordPress-FluxC-Android/pull/2240) PR, which upgraded `WCAndroidDatabase` from version `5` to `6`, the `6.json` migration file was added as well (see [commit](https://github.com/wordpress-mobile/WordPress-FluxC-Android/pull/2240/commits/2736e8a8fd5e2179c6cfbffc09d2eacbeb98793a)).

As such, I am recommending to add the missing `7.json` migration file that will accompany the latest `WCAndroidDatabase` `6` to `7` upgrade. Also, mind the fact that unless this `7.json` migration file is added to version control it will keep being automatically added as an unversioned file by the IDE.

PS: This update is not mandatory and will not fail the migration and as such upgrading the app. It is just a good practice to have this file committed in the version control system and have it in the codebase. For more info check the [documentation](https://developer.android.com/reference/android/arch/persistence/room/Database#exportSchema()).

### Assignment

I am assigning this to you @nbradbury since you were the last to update the `WCAndroidDatabase` and have more context on it.

**Comment by nbradbury** [comment]
@ParaskP7 I believe this was addressed in #2255

**Comment by ParaskP7** [comment]
👋 @nbradbury and 😅 !

Indeed it was, I updated the `trunk` this morning and didn't update since, thanks for the update! 🥇
