### ISSUE TITLE
Woo: Shipping phone information is never saved

### ISSUE THREAD

**Issue by atorresveiga** [wordpress-mobile/WordPress-FluxC-Android#2516]
While working on Address validation, I note that the phone shipping information is never updated/saved and always displays an empty value.
Expected behavior: The shipping phone information is displayed correctly and can be updated.

**Comment by wzieba** [comment]
👋 I never understood the difference between `Order#shippingPhone` and `Order#shippingAddress#phone`. Are those the same? Should we merge it? Maybe one of them is not needed?

This way or another, I think we should find a way not to have two different "shipping phones" in the Order.
