### ISSUE TITLE
[Application Passwords] Deleting a password will clear all site's passwords

### ISSUE THREAD

**Issue by hichamboushaba** [wordpress-mobile/WordPress-FluxC-Android#2632]
Currently, we pass the `Application Password`'s name in the delete request, but the [API](https://github.com/WordPress/WordPress/blob/4191d80f708b99386f30d39aed129e8bff3fe752/wp-includes/rest-api/endpoints/class-wp-rest-application-passwords-controller.php#L78) doesn't support this flow, as it expects a UUID instead of the name. So it considers the body empty, and proceeds to clearing all of the passwords.

**Comment by hafizrahman** [comment]
While I'll still work on the fix on the app side, this also feels like something that could be improved in the core side as well. Seems dangerous to accept empty UUID to mean to delete every single existing application password. What do you think?

**Comment by hichamboushaba** [comment]
> While I'll still work on the fix on the app side, this also feels like something that could be improved in the core side as well. Seems dangerous to accept empty UUID to mean to delete every single existing application password. What do you think?

It's not accepting empty UUID per se, the API offers two endpoints, the first is [`/users/me/application-passwords/`](https://github.com/WordPress/WordPress/blob/10ad5f0d4d0d143e2d4fbe56f40b630a5d748aa2/wp-includes/rest-api/endpoints/class-wp-rest-application-passwords-controller.php#L37) and the other is [`/users/me/application-passwords/{uuid}`](https://github.com/WordPress/WordPress/blob/4191d80f708b99386f30d39aed129e8bff3fe752/wp-includes/rest-api/endpoints/class-wp-rest-application-passwords-controller.php#L78), so they are two different paths. Because of this, I'd say the API is working as expected, it's our fault for not checking the proper usage before adding it.

**Comment by hafizrahman** [comment]
Oh TIL I think I might have added the wrong fix. Let me update my PRs.
