### ISSUE TITLE
New store: MediaStore

### ISSUE THREAD

**Issue by maxme** [wordpress-mobile/WordPress-FluxC-Android#39]

**Comment by tonyr59h** [comment]
WPAndroid currently uses XML-RPC to create, edit, and fetch media items from both WordPress.com and self-hosted sites. `MediaStore` will utilize the WordPress.com REST API if it is available for a site. The XML-RPC interface is being ported into the project and will still be used for self-hosted sites and Jetpack sites that have opted not to enable REST.

### WordPress.com Rest API
- [X] Pull all media items ([ref](https://developer.wordpress.com/docs/api/1.1/get/sites/%24site/media))
- [X] Pull a single media item ([ref](https://developer.wordpress.com/docs/api/1.1/get/sites/%24site/media/%24media_ID))
- [X] Push changes to a media item ([ref](https://developer.wordpress.com/docs/api/1.1/post/sites/%24site/media/%24media_ID))
- [ ] Push a new media item; requires multipart support ([ref](https://developer.wordpress.com/docs/api/1.1/post/sites/%24site/media/new))
- [X] Delete a media item ([ref](https://developer.wordpress.com/docs/api/1.1/post/sites/%24site/media/%24media_ID/delete))

### Self-hosted XML-RPC API
- [X] Pull all media items ([ref](https://codex.wordpress.org/XML-RPC_WordPress_API/Media#wp.getMediaLibrary))
- [X] Pull a single media item ([ref](https://codex.wordpress.org/XML-RPC_WordPress_API/Media#wp.getMediaItem))
- [ ] Push a new media item ([ref](https://codex.wordpress.org/XML-RPC_WordPress_API/Media#wp.uploadFile))

### Database

#### Functionality implemented in WordPressDB
- [ ] `saveMediaFile`- same functionality as `insertOrUpdateMedia`
- [ ] `getFirstMediaFileForBlog` - dropped; worst case during integration use `getAllMedia` and selected first media item
- [ ] `getMediaFilesForBlog` - implemented as `getAllMedia`
- [ ] `getMediaFile` - implemented as `getMediaById`
- [ ] `getMediaFilesForBlog` (with search term) - add search term to `GET_MEDIA` payload
- [ ] `getMediaUrlByVideoPressId`
- [ ] `getMediaThumbnailUrl`
- [ ] `getMediaCountAll`
- [ ] `mediaFileExists`
- [ ] `getMediaImagesForBlog`
- [ ] `getMediaImagesForBlog` with filter
- [ ] `getMediaCountImages`
- [ ] `getMediaUnattachedForBlog`
- [ ] `getMediaCountUnattached`
- [ ] `getMediaFilesForBlog`
- [ ] `getMediaFiles`
- [ ] `getMediaFile`
- [ ] `getMediaFile`
- [ ] `deleteMediaFilesForPost`
- [ ] `getMediaUploadQueue`
- [ ] `updateMediaUploadState`
- [ ] `updateMediaLocalToRemoteId`
- [ ] `updateMediaFile`
- [ ] `setMediaUploadingToFailed`
- [ ] `clearMediaUploaded` - unused, remove
- [ ] `deleteMediaFile`
- [ ] `setMediaFilesMarkedForDelete`
- [ ] `setMediaFilesMarkedForDeleted`
- [ ] `deleteFilesMarkedForDeleted`
- [ ] `getMediaDeleteQueueItem`
- [ ] `getMediaDeleteQueueItems` - unused, remove
- [ ] `hasMediaDeleteQueueItems`

**Comment by oguzkocer** [comment]
@tonyr59h I think `getMediaFilesForBlog(String blogId, long startDate, long endDate)` is missing from this list.

**Comment by aforcier** [comment]
Added in #122.
