### ISSUE TITLE
Rename getSelfHostedSites, drop useless getters (getJetpackSites) in the site store

### ISSUE THREAD

**Issue by maxme** [wordpress-mobile/WordPress-FluxC-Android#428]
Rename site getters in the SiteStore, some of them are misleading.

We probably want something like `getSitesAccessedViaWpComRest` and `getSitesAccessedViaXMLRPC`.

cc @aforcier

**Comment by aforcier** [comment]
Fixed in https://github.com/wordpress-mobile/WordPress-FluxC-Android/pull/430.
