### ISSUE TITLE
Handle IllegalArgumentException in sanitizeUrl in SelfHostedEndpointFinder

### ISSUE THREAD

**Issue by mzorz** [wordpress-mobile/WordPress-FluxC-Android#434]
When an invalid URL (too long, unable to translate to punyCode, or whatever other reasons, such as, but not least:

`U_IDNA_LABEL_TOO_LONG_ERROR`
`U_STRINGPREP_PROHIBITED_ERROR`
`Caused by android.icu.text.StringPrepParseException: The labels in the input are too long. Length > 63.`

(and others found in prod), an IllegalArgumentException is thrown and is sent up the try/catch hierarchy. We should manage it at this level and throw a `DiscoveryException` up instead

**Comment by tonyr59h** [comment]
Closed via #437

**Comment by maxme** [comment]
I wonder if this can be an underlying issue in `UrlUtils.convertUrlToPunycodeIfNeeded` - I'll double check.

**Comment by maxme** [comment]
Ignore me, the utils method look OK - https://github.com/wordpress-mobile/WordPress-Utils-Android/commit/49c11d0cd221b68e6c5c281dfac9a293435377bb
