### ISSUE TITLE
Clean token and account on INVALID_TOKEN error

### ISSUE THREAD

**Issue by aforcier** [wordpress-mobile/WordPress-FluxC-Android#462]
We receive an `invalid_token` error from WP.com if the token used by the app has been invalidated. In this case we should flush the token and account data - otherwise it becomes impossible to sign back into WordPress.com.

**Comment by designsimply** [comment]
Adding to Groundskeeping because this issue is a blocker for https://github.com/wordpress-mobile/WordPress-Android/issues/7772.
