### ISSUE TITLE
/sites/$site endpoint implementation only checks for host part of URI

### ISSUE THREAD

**Issue by hypest** [wordpress-mobile/WordPress-FluxC-Android#518]
Currently, FluxC only picks up the host part of the requested URI to test against the `/sites/$siteAddress` API endpoint (see https://github.com/wordpress-mobile/WordPress-FluxC-Android/blob/c8e6de55afe86befe739df92d592f469727e0766/fluxc/src/main/java/org/wordpress/android/fluxc/network/rest/wpcom/site/SiteRestClient.java#L330), but a site can exist in a subfolder under that host.

For example, these test sites (http://do.wpmt.co/) won't be correctly identified because of this issue.

**Comment by aforcier** [comment]
Turns out encoding the slashes (`/` --> `%2F`) works, thanks for suggesting that @hypest. I thought we had tried this when we implemented `FETCH_WPCOM_SITE_BY_URL` but I guess we didn't!

**Comment by hypest** [comment]
While at it, we might need to urlencode the whole of URI anyway @aforcier.
