### ISSUE TITLE
Inject UploadStore in PostStore and MediaStore

### ISSUE THREAD

**Issue by aforcier** [wordpress-mobile/WordPress-FluxC-Android#559]
As an enhancement to the `UploadStore` addition (#533), we can inject the `UploadStore` into the `PostStore` and `MediaStore` instead of adding it to the constructor for those classes.

From my research so far, there's a blocker to that, which is that we can't use modules inside FluxC without a `Component`. Setting up a component inside FluxC will cause us to have two graphs when running inside an app, and the `UploadStore` won't actually be hooked up to the same `Dispatcher` as the rest of FluxC.

We can, however, use normal `@Inject` constructor annotation to supply `UploadStore` (we already do this for all stores), and this will allow the `PostStore` and `MediaStore` to inject it.

The problem is that we currently use both `@Inject` constructor annotations and `@Provides` methods (in `ReleaseStoreModule`) for our stores. This is redundant though it hasn't harmed us  so far. In this case, however, since `@Provides` seems to take priority, injecting `UploadStore` within FluxC doesn't actually work (because the library can't see the `@Provides` part of the Dagger graph).

Simply dropping `ReleaseStoreModule` fixes the problem, and I think this is a good solution. If we end up wanting a `MockedStoreModule`, we can make one and use `@Named` to differentiate those stores when injecting from the tests.

**Comment by mzorz** [comment]
Closing via #562
