### ISSUE TITLE
ThemeStore: Create separate table for themes with no associated site

### ISSUE THREAD

**Issue by tonyr59h** [wordpress-mobile/WordPress-FluxC-Android#574]
More info in #570.

WP.com themes are stored in the database and all have a site ID of `0`. Themes associated with a site (installed on Jetpack, for example) are stored in the same database with the appropriate site ID. Future table enhancements have the potential to create an ugly situation out of this, we should keep WP.com themes in a separate table to avoid problems.

**Comment by tonyr59h** [comment]
58b779d42b49418a7b5d45ccf637ad1a4c90ec12 adds a flag to `ThemeModel` that identifies WP.com themes, making this issue obsolete.

**Comment by aforcier** [comment]
@tonyr59h I agree that the flag to `ThemeModel` is a safer solution that originally, but that doesn't seem to me to mitigate the original risk of having entries in the table for a non-existent site with id `0`. One potential issue would be if we introduced foreign key constraints to all site id-linked tables - the `ThemeModelTable` would still require there to be a site with id `0` for the WP.com themes, and we'd be unable to store WP.com themes.

I suppose we can just do a migration at that point if we need to and re-fetch. But we should maybe keep this issue open. What's your take?
