### ISSUE TITLE
Check `siteId` from .org site becoming jetpack sites

### ISSUE THREAD

**Issue by maxme** [wordpress-mobile/WordPress-FluxC-Android#58]
We're currently using siteId + site url as identifiers, but I think we might encounter problems if a .org site install jetpack and gets refreshed in the app.

See [this note](https://github.com/wordpress-mobile/WordPress-Stores-Android/blob/65a3da05e6548c69e1fd7952ecc229a239240bb9/WordPressStores/src/main/java/org/wordpress/android/stores/persistence/SiteSqlUtils.java#L42-L42) in code.

**Comment by aforcier** [comment]
This also causes a problem when logging into a self-hosted site already present as a Jetpack site (from logging into WP.com): https://github.com/wordpress-mobile/WordPress-Android/pull/4455#issuecomment-242238265

**Comment by oguzkocer** [comment]
> I think we might encounter problems if a .org site install jetpack and gets refreshed in the app.

Shouldn't we just update the current record if this happens? I can't imagine we want to have 2 different records of the same site.

> This also causes a problem when logging into a self-hosted site already present as a Jetpack site

I think we should just prevent this, if the site is already in the DB as a jetpack site, there is no benefit of adding it as a self-hosted as well or update it.

**Comment by maxme** [comment]
Fixed via #285
