### ISSUE TITLE
Correctly localize account/site creation

### ISSUE THREAD

**Issue by aforcier** [wordpress-mobile/WordPress-FluxC-Android#609]
At the moment, creating a new WordPress.com account or site ignores the user's locale and sets up the account/site in English.

For account creation, we need to add a `locale=[language-code]` (e.g. `locale=jp`) to the [`POST` request body](https://github.com/wordpress-mobile/WordPress-FluxC-Android/blob/6693ea428726c5dc10268b7ca33de255fdaaa87c/fluxc/src/main/java/org/wordpress/android/fluxc/network/rest/wpcom/account/AccountRestClient.java#L433-L439).

For site creation, it looks like at least part of the problem is that we're [passing the device locale in `lang_id`](https://github.com/wordpress-mobile/WordPress-FluxC-Android/blob/6693ea428726c5dc10268b7ca33de255fdaaa87c/fluxc/src/main/java/org/wordpress/android/fluxc/network/rest/wpcom/site/SiteRestClient.java#L175), but that field is actually supposed to be a number representing a WordPress.com locale code.

**Comment by aforcier** [comment]
@0nko what's the reasoning for closing this one? AFAIK the site creation aspect is still unaddressed.

**Comment by elibud** [comment]
@oguzkocer @malinajirka does anything change for this one with the new flow? Can you take care of fixing it?

**Comment by oguzkocer** [comment]
@elibud New flow uses the old endpoint, so nothing changes. However, we could definitely take care of it. Would you like this to be a must in v1 or a lower priority? I think it'll be in the same version regardless, but I am asking just in case.

**Comment by elibud** [comment]
Well, it has been open since November so I'm fine with it being lower priority, thanks @oguzkocer

**Comment by elibud** [comment]
November 2017 😱
