### ISSUE TITLE
Add discovery tests for sites requiring 'advanced' discovery (e.g. rsd lookup)

### ISSUE THREAD

**Issue by maxme** [wordpress-mobile/WordPress-FluxC-Android#62]
We need to setup these sites first.

**Comment by aforcier** [comment]
We should also test for hosts blocking XML-RPC (and make sure we report that to the user properly).

**Comment by aforcier** [comment]
Both items are addressed in https://github.com/wordpress-mobile/WordPress-FluxC-Android/pull/224.
