### ISSUE TITLE
Support featured plugins directory

### ISSUE THREAD

**Issue by nbradbury** [wordpress-mobile/WordPress-FluxC-Android#696]
Now that we have [an endpoint](https://github.com/Automattic/wp-calypso/pull/21627) for featured plugins, we should support it in FluxC and then WPAndroid. 

Note that this is a wp.com endpoint - https://public-api.wordpress.com/wpcom/v2/plugins/featured

cc: @oguzkocer

**Comment by oguzkocer** [comment]
Added in #727
