### ISSUE TITLE
Implement dangerouslyDeleteAllContent

### ISSUE THREAD

**Issue by aforcier** [wordpress-mobile/WordPress-FluxC-Android#76]
We'll need to implement our own version of [WordPressDB.dangerouslyDeleteAllContent](https://github.com/wordpress-mobile/WordPress-Android/blob/61ba7d2df6d231aa1e657c677c33545c497d4e5a/WordPress/src/main/java/org/wordpress/android/WordPressDB.java#L799) as part of the sign out flow.

**Comment by maxme** [comment]
Fixed via https://github.com/wordpress-mobile/WordPress-FluxC-Android/pull/255
