### ISSUE TITLE
Switch from metaWeblog to wp XML-RPC methods

### ISSUE THREAD

**Issue by aforcier** [wordpress-mobile/WordPress-FluxC-Android#83]
We're currently using `metaWeblog` methods in several places (getting posts, editing posts, creating new posts) that since have equivalent `wp` methods. We should switch over to `wp` where feasible (or document why we're keeping `metaWeblog` where not feasible).

**Comment by aforcier** [comment]
This is already done as part of the work-in-progress [PostStore implementation](https://github.com/wordpress-mobile/WordPress-FluxC-Android/pull/77). We can close this issue when that branch is merged.

**Comment by tonyr59h** [comment]
> We can close this issue when that branch is merged.

🎉
