### ISSUE TITLE
Rename all instances of 'blog' to 'site'

### ISSUE THREAD

**Issue by maxme** [wordpress-mobile/WordPress-FluxC-Android#98]
And all other s/Blog/Site/ even if it comes from the API. We don't want to mix names like in: `mSiteStore.getSiteById(mAccountStore.getPrimaryBlogId())`

**Comment by aforcier** [comment]
`s/getPrimaryBlogId/getPrimarySiteId` was done in https://github.com/wordpress-mobile/WordPress-FluxC-Android/pull/138. Leaving this issue open as there are probably other cases where we need to replace `blog` with `site`.

**Comment by tonyr59h** [comment]
Just renamed all the MediaStore instances in e31de03880a317a95d9a7d5c0d1a270ab019ae99. I saw `blog` being used mostly in accounts, authentication, and sites classes. It shouldn't be too much effort to rename the remaining instances.

**Comment by maxme** [comment]
I'm closing this one (was fixed in the MediaStore branch).
